//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum BinAddLiquidityStrategy {
Uniform {
current_bin_index: i32,
lower_bin_index: i32,
upper_bin_index: i32,
amount_x_to_deposit: u64,
amount_y_to_deposit: u64,
x_current_bin: u64,
y_current_bin: u64,
},
CurrentTick(i32),
}


