//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::RebalanceAutodriftWindow;
use crate::types::RebalanceAutodriftStep;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RebalanceAutodriftState {
pub last_window: RebalanceAutodriftWindow,
pub current_window: RebalanceAutodriftWindow,
pub step: RebalanceAutodriftStep,
}


