//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Accounts.
pub struct ChangePool {
      
              
          pub admin_authority: solana_program::pubkey::Pubkey,
          
              
          pub strategy: solana_program::pubkey::Pubkey,
          
              
          pub old_position: solana_program::pubkey::Pubkey,
          
              
          pub base_vault_authority: solana_program::pubkey::Pubkey,
          
              
          pub new_pool: solana_program::pubkey::Pubkey,
          
              
          pub strategy_reward_vault0_or_base_vault_authority: solana_program::pubkey::Pubkey,
          
              
          pub strategy_reward_vault1_or_base_vault_authority: solana_program::pubkey::Pubkey,
          
              
          pub strategy_reward_vault2_or_base_vault_authority: solana_program::pubkey::Pubkey,
      }

impl ChangePool {
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(8+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            self.admin_authority,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.strategy,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.old_position,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.base_vault_authority,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.new_pool,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.strategy_reward_vault0_or_base_vault_authority,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.strategy_reward_vault1_or_base_vault_authority,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.strategy_reward_vault2_or_base_vault_authority,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = ChangePoolInstructionData::new().try_to_vec().unwrap();
    
    solana_program::instruction::Instruction {
      program_id: crate::YVAULTS_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ChangePoolInstructionData {
            discriminator: [u8; 8],
      }

impl ChangePoolInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [141, 221, 123, 235, 35, 9, 145, 201],
                  }
  }
}

impl Default for ChangePoolInstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `ChangePool`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` admin_authority
                ///   1. `[writable]` strategy
          ///   2. `[]` old_position
          ///   3. `[]` base_vault_authority
          ///   4. `[]` new_pool
          ///   5. `[]` strategy_reward_vault0_or_base_vault_authority
          ///   6. `[]` strategy_reward_vault1_or_base_vault_authority
          ///   7. `[]` strategy_reward_vault2_or_base_vault_authority
#[derive(Clone, Debug, Default)]
pub struct ChangePoolBuilder {
            admin_authority: Option<solana_program::pubkey::Pubkey>,
                strategy: Option<solana_program::pubkey::Pubkey>,
                old_position: Option<solana_program::pubkey::Pubkey>,
                base_vault_authority: Option<solana_program::pubkey::Pubkey>,
                new_pool: Option<solana_program::pubkey::Pubkey>,
                strategy_reward_vault0_or_base_vault_authority: Option<solana_program::pubkey::Pubkey>,
                strategy_reward_vault1_or_base_vault_authority: Option<solana_program::pubkey::Pubkey>,
                strategy_reward_vault2_or_base_vault_authority: Option<solana_program::pubkey::Pubkey>,
                __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl ChangePoolBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn admin_authority(&mut self, admin_authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.admin_authority = Some(admin_authority);
                    self
    }
            #[inline(always)]
    pub fn strategy(&mut self, strategy: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.strategy = Some(strategy);
                    self
    }
            #[inline(always)]
    pub fn old_position(&mut self, old_position: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.old_position = Some(old_position);
                    self
    }
            #[inline(always)]
    pub fn base_vault_authority(&mut self, base_vault_authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.base_vault_authority = Some(base_vault_authority);
                    self
    }
            #[inline(always)]
    pub fn new_pool(&mut self, new_pool: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.new_pool = Some(new_pool);
                    self
    }
            #[inline(always)]
    pub fn strategy_reward_vault0_or_base_vault_authority(&mut self, strategy_reward_vault0_or_base_vault_authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.strategy_reward_vault0_or_base_vault_authority = Some(strategy_reward_vault0_or_base_vault_authority);
                    self
    }
            #[inline(always)]
    pub fn strategy_reward_vault1_or_base_vault_authority(&mut self, strategy_reward_vault1_or_base_vault_authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.strategy_reward_vault1_or_base_vault_authority = Some(strategy_reward_vault1_or_base_vault_authority);
                    self
    }
            #[inline(always)]
    pub fn strategy_reward_vault2_or_base_vault_authority(&mut self, strategy_reward_vault2_or_base_vault_authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.strategy_reward_vault2_or_base_vault_authority = Some(strategy_reward_vault2_or_base_vault_authority);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = ChangePool {
                              admin_authority: self.admin_authority.expect("admin_authority is not set"),
                                        strategy: self.strategy.expect("strategy is not set"),
                                        old_position: self.old_position.expect("old_position is not set"),
                                        base_vault_authority: self.base_vault_authority.expect("base_vault_authority is not set"),
                                        new_pool: self.new_pool.expect("new_pool is not set"),
                                        strategy_reward_vault0_or_base_vault_authority: self.strategy_reward_vault0_or_base_vault_authority.expect("strategy_reward_vault0_or_base_vault_authority is not set"),
                                        strategy_reward_vault1_or_base_vault_authority: self.strategy_reward_vault1_or_base_vault_authority.expect("strategy_reward_vault1_or_base_vault_authority is not set"),
                                        strategy_reward_vault2_or_base_vault_authority: self.strategy_reward_vault2_or_base_vault_authority.expect("strategy_reward_vault2_or_base_vault_authority is not set"),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `change_pool` CPI accounts.
  pub struct ChangePoolCpiAccounts<'a, 'b> {
          
                    
              pub admin_authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub strategy: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub old_position: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub new_pool: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub strategy_reward_vault0_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub strategy_reward_vault1_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub strategy_reward_vault2_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `change_pool` CPI instruction.
pub struct ChangePoolCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub admin_authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub strategy: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub old_position: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub new_pool: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub strategy_reward_vault0_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub strategy_reward_vault1_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub strategy_reward_vault2_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>,
        }

impl<'a, 'b> ChangePoolCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: ChangePoolCpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              admin_authority: accounts.admin_authority,
              strategy: accounts.strategy,
              old_position: accounts.old_position,
              base_vault_authority: accounts.base_vault_authority,
              new_pool: accounts.new_pool,
              strategy_reward_vault0_or_base_vault_authority: accounts.strategy_reward_vault0_or_base_vault_authority,
              strategy_reward_vault1_or_base_vault_authority: accounts.strategy_reward_vault1_or_base_vault_authority,
              strategy_reward_vault2_or_base_vault_authority: accounts.strategy_reward_vault2_or_base_vault_authority,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(8+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            *self.admin_authority.key,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.strategy.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.old_position.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.base_vault_authority.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.new_pool.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.strategy_reward_vault0_or_base_vault_authority.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.strategy_reward_vault1_or_base_vault_authority.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.strategy_reward_vault2_or_base_vault_authority.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = ChangePoolInstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::YVAULTS_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(9 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.admin_authority.clone());
                        account_infos.push(self.strategy.clone());
                        account_infos.push(self.old_position.clone());
                        account_infos.push(self.base_vault_authority.clone());
                        account_infos.push(self.new_pool.clone());
                        account_infos.push(self.strategy_reward_vault0_or_base_vault_authority.clone());
                        account_infos.push(self.strategy_reward_vault1_or_base_vault_authority.clone());
                        account_infos.push(self.strategy_reward_vault2_or_base_vault_authority.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `ChangePool` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` admin_authority
                ///   1. `[writable]` strategy
          ///   2. `[]` old_position
          ///   3. `[]` base_vault_authority
          ///   4. `[]` new_pool
          ///   5. `[]` strategy_reward_vault0_or_base_vault_authority
          ///   6. `[]` strategy_reward_vault1_or_base_vault_authority
          ///   7. `[]` strategy_reward_vault2_or_base_vault_authority
#[derive(Clone, Debug)]
pub struct ChangePoolCpiBuilder<'a, 'b> {
  instruction: Box<ChangePoolCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ChangePoolCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(ChangePoolCpiBuilderInstruction {
      __program: program,
              admin_authority: None,
              strategy: None,
              old_position: None,
              base_vault_authority: None,
              new_pool: None,
              strategy_reward_vault0_or_base_vault_authority: None,
              strategy_reward_vault1_or_base_vault_authority: None,
              strategy_reward_vault2_or_base_vault_authority: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn admin_authority(&mut self, admin_authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin_authority = Some(admin_authority);
                    self
    }
      #[inline(always)]
    pub fn strategy(&mut self, strategy: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.strategy = Some(strategy);
                    self
    }
      #[inline(always)]
    pub fn old_position(&mut self, old_position: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.old_position = Some(old_position);
                    self
    }
      #[inline(always)]
    pub fn base_vault_authority(&mut self, base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.base_vault_authority = Some(base_vault_authority);
                    self
    }
      #[inline(always)]
    pub fn new_pool(&mut self, new_pool: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.new_pool = Some(new_pool);
                    self
    }
      #[inline(always)]
    pub fn strategy_reward_vault0_or_base_vault_authority(&mut self, strategy_reward_vault0_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.strategy_reward_vault0_or_base_vault_authority = Some(strategy_reward_vault0_or_base_vault_authority);
                    self
    }
      #[inline(always)]
    pub fn strategy_reward_vault1_or_base_vault_authority(&mut self, strategy_reward_vault1_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.strategy_reward_vault1_or_base_vault_authority = Some(strategy_reward_vault1_or_base_vault_authority);
                    self
    }
      #[inline(always)]
    pub fn strategy_reward_vault2_or_base_vault_authority(&mut self, strategy_reward_vault2_or_base_vault_authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.strategy_reward_vault2_or_base_vault_authority = Some(strategy_reward_vault2_or_base_vault_authority);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
        let instruction = ChangePoolCpi {
        __program: self.instruction.__program,
                  
          admin_authority: self.instruction.admin_authority.expect("admin_authority is not set"),
                  
          strategy: self.instruction.strategy.expect("strategy is not set"),
                  
          old_position: self.instruction.old_position.expect("old_position is not set"),
                  
          base_vault_authority: self.instruction.base_vault_authority.expect("base_vault_authority is not set"),
                  
          new_pool: self.instruction.new_pool.expect("new_pool is not set"),
                  
          strategy_reward_vault0_or_base_vault_authority: self.instruction.strategy_reward_vault0_or_base_vault_authority.expect("strategy_reward_vault0_or_base_vault_authority is not set"),
                  
          strategy_reward_vault1_or_base_vault_authority: self.instruction.strategy_reward_vault1_or_base_vault_authority.expect("strategy_reward_vault1_or_base_vault_authority is not set"),
                  
          strategy_reward_vault2_or_base_vault_authority: self.instruction.strategy_reward_vault2_or_base_vault_authority.expect("strategy_reward_vault2_or_base_vault_authority is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct ChangePoolCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            admin_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                strategy: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                old_position: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                base_vault_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                new_pool: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                strategy_reward_vault0_or_base_vault_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                strategy_reward_vault1_or_base_vault_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                strategy_reward_vault2_or_base_vault_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

