//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#collateral_infos;
  pub(crate) mod r#global_config;
  pub(crate) mod r#personal_position_state;
  pub(crate) mod r#pool_state;
  pub(crate) mod r#position;
  pub(crate) mod r#protocol_position_state;
  pub(crate) mod r#scope_chain_account;
  pub(crate) mod r#terms_signature;
  pub(crate) mod r#whirlpool;
  pub(crate) mod r#whirlpool_strategy;

  pub use self::r#collateral_infos::*;
  pub use self::r#global_config::*;
  pub use self::r#personal_position_state::*;
  pub use self::r#pool_state::*;
  pub use self::r#position::*;
  pub use self::r#protocol_position_state::*;
  pub use self::r#scope_chain_account::*;
  pub use self::r#terms_signature::*;
  pub use self::r#whirlpool::*;
  pub use self::r#whirlpool_strategy::*;

