//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::{pubkey, pubkey::Pubkey};

/// `yvaults` program ID.
pub const YVAULTS_ID: Pubkey = pubkey!("6LtLpnUFNByNXLyCoK9wA2MykKAmQNZKBdY8s47dehDc");
